"""
PDF Report Generator (Pro Feature)
Generate professional OSINT reports
"""

from datetime import datetime
from typing import Dict, List
from pathlib import Path
import json


class PDFReportGenerator:
    """Generate PDF reports from OSINT data"""
    
    def __init__(self):
        self.report_data = {}
    
    def generate_report(self, data: Dict, output_path: str) -> str:
        """
        Generate PDF report (Pro feature)
        
        In Pro version, this uses reportlab to create actual PDFs
        Free version gets HTML report instead
        """
        output_path = Path(output_path)
        
        # For now, generate HTML report
        html_path = output_path.with_suffix('.html')
        html = self._generate_html_report(data)
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return str(html_path)
    
    def _generate_html_report(self, data: Dict) -> str:
        """Generate HTML report"""
        target = data.get('target', 'Unknown')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>OSINT Report - {target}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            max-width: 1200px;
            margin: 40px auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
        }}
        .section {{
            background: white;
            padding: 25px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        .finding {{
            background: #f9f9f9;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid #667eea;
            border-radius: 4px;
        }}
        .alert {{
            background: #fff3cd;
            border-left-color: #ffc107;
        }}
        .success {{
            background: #d4edda;
            border-left-color: #28a745;
        }}
        .footer {{
            text-align: center;
            color: #666;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #667eea;
            color: white;
        }}
        .watermark {{
            background: #e3f2fd;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            margin-top: 30px;
            border: 2px dashed #2196f3;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔍 OSINT Intelligence Report</h1>
        <p><strong>Target:</strong> {target}</p>
        <p><strong>Generated:</strong> {timestamp}</p>
    </div>
"""
        
        # Add results sections
        results = data.get('results', {})
        
        if 'email' in results:
            html += self._email_section(results['email'])
        
        if 'username' in results:
            html += self._username_section(results['username'])
        
        if 'breaches' in results:
            html += self._breach_section(results['breaches'])
        
        if 'whois' in results:
            html += self._whois_section(results['whois'])
        
        # Watermark for free version
        html += """
    <div class="watermark">
        <h3>💎 Upgrade to OSINT Tool Pro</h3>
        <p>Get PDF reports, bulk search, scheduled monitoring, and more!</p>
        <p><strong>Only $19.99 one-time</strong></p>
    </div>
    
    <div class="footer">
        <p>Generated by OSINT Tool - Professional Intelligence Gathering</p>
        <p>Report ID: """ + datetime.now().strftime('%Y%m%d%H%M%S') + """</p>
    </div>
</body>
</html>
"""
        
        return html
    
    def _email_section(self, data: Dict) -> str:
        valid = '✅' if data.get('valid_format') else '❌'
        disposable = '⚠️ Yes' if data.get('disposable') else '✅ No'
        
        section = f"""
    <div class="section">
        <h2>📧 Email Analysis</h2>
        <table>
            <tr><th>Property</th><th>Value</th></tr>
            <tr><td>Email</td><td>{data.get('email', 'N/A')}</td></tr>
            <tr><td>Valid Format</td><td>{valid}</td></tr>
            <tr><td>Domain</td><td>{data.get('domain', 'N/A')}</td></tr>
            <tr><td>Disposable</td><td>{disposable}</td></tr>
        </table>
"""
        
        if data.get('social_profiles'):
            section += "<h3>Potential Social Profiles</h3>"
            for platform, url in data['social_profiles'].items():
                section += f'<div class="finding"><strong>{platform}:</strong> <a href="{url}">{url}</a></div>'
        
        section += "</div>"
        return section
    
    def _username_section(self, data: Dict) -> str:
        section = f"""
    <div class="section">
        <h2>👤 Username Search Results</h2>
        <p><strong>Username:</strong> {data.get('username', 'N/A')}</p>
        <p><strong>Platforms Checked:</strong> {data.get('total_platforms', 0)}</p>
        <p><strong>Found:</strong> {data.get('found_count', 0)}</p>
"""
        
        if data.get('found'):
            section += "<h3>✅ Confirmed Accounts</h3>"
            for account in data['found']:
                section += f"""
        <div class="finding success">
            <strong>{account['name']}</strong><br>
            <a href="{account['url']}">{account['url']}</a>
"""
                if account.get('status'):
                    section += f"<br><em>{account['status']}</em>"
                section += "</div>"
        
        section += "</div>"
        return section
    
    def _breach_section(self, data: Dict) -> str:
        count = data.get('breach_count', 0)
        alert_class = 'alert' if count > 0 else 'success'
        
        section = f"""
    <div class="section">
        <h2>🔒 Data Breach Check</h2>
        <div class="finding {alert_class}">
            <strong>Total Breaches Found:</strong> {count}
        </div>
"""
        
        if data.get('breaches'):
            section += "<h3>⚠️ Breach Details</h3>"
            for breach in data['breaches']:
                section += f"""
        <div class="finding alert">
            <h4>{breach.get('name', 'Unknown')}</h4>
            <p><strong>Date:</strong> {breach.get('date', 'Unknown')}</p>
            <p><strong>Compromised Data:</strong> {', '.join(breach.get('data_types', []))}</p>
            <p>{breach.get('description', '')}</p>
        </div>
"""
        
        section += "</div>"
        return section
    
    def _whois_section(self, data: Dict) -> str:
        registered = '✅ Yes' if data.get('registered') else '❌ No'
        
        section = f"""
    <div class="section">
        <h2>🌐 WHOIS Information</h2>
        <table>
            <tr><th>Property</th><th>Value</th></tr>
            <tr><td>Domain</td><td>{data.get('domain', 'N/A')}</td></tr>
            <tr><td>Registered</td><td>{registered}</td></tr>
"""
        
        if data.get('registrar'):
            section += f"<tr><td>Registrar</td><td>{data['registrar']}</td></tr>"
        if data.get('creation_date'):
            section += f"<tr><td>Created</td><td>{data['creation_date']}</td></tr>"
        if data.get('expiration_date'):
            section += f"<tr><td>Expires</td><td>{data['expiration_date']}</td></tr>"
        
        section += "</table></div>"
        return section
